---
title: "Long term performance of bad performing catchments"
subtitle: "Sim & SUFI data"
author: "Caleb Scutt"
format:
  html:
    page-layout: full
    toc: true
    code-fold: true
    fig-width: 10
    fig-height: 5
    embed-resources: true
    theme: flatly
  typst:
    toc: true
    fig-width: 7
    fig-height: 5
    margin:
      x: 1in
      y: 1in
    fontsize: 11pt
    section-numbering: 1.1.1
    keep-typ: false
execute:
  warning: false
  message: false
---



```{r echo = FALSE}
## load packages and functions
library(data.table)
library(ggplot2)
library(lubridate)
library(gtools)
library(sf)
library(grid)
library(gridExtra)
library(patchwork)
library(gt)
source("../functions/utility.R")
source("../functions/extract.g2g.qt.R")
source("../functions/qt.exceed.R")
source("../functions/plot.wales.R")
source("../functions/obs.mod.stats.R")
```



```{r}
sim_runs <- list.dirs("../data/g2g_data/Sim_g2g_run/", full.names = FALSE, recursive = FALSE)
sufi_runs <- list.dirs("../data/g2g_data/SUFI_g2g_run/", full.names = FALSE, recursive = FALSE)
sim_files <- paste0(sim_runs, "/base_.dat_WA")
sufi_files <- paste0(sufi_runs, "/base_.dat_WA")
sim_path <- file.path("..", "data", "g2g_data","Sim_g2g_run")
sufi_path <- file.path("..", "data", "g2g_data","SUFI_g2g_run")




## read in mod and obs
sim_ts <- read.time.series(sim_files[19:22],sim_path, output = "model")
sufi_ts <- read.time.series(sufi_files[19:22],sufi_path, output = "model")
obs_ts <- read.time.series(sufi_files[19:22],sufi_path, output = "observed")

mod_ts <- list(sim = sim_ts, sufi = sufi_ts)

## read in the events
events <- fread("../data/notable_events.csv")
events_pre_2022 <- events[Year <= 2021,]
## read in the catchment metadata
catchments <- fread("../data/cdata/catchment_cdata_EA-NRW.csv", fill = Inf)
## filter by wales
wales_cdata <- catchments[Region. == "Wales", ]


```